#! /bin/sh


nitrogen --restore &

pactl set-sink-volume 0 0%

picom-pijulius --animations \
   --animation-for-open-window zoom \
   --animation-for-transient-window zoom \
   --no-fading-openclose \
   -I 1 \
   -O 1 &

kanata --cfg ~/.config/kanata/config.kbd &
setxkbmap -option caps:swapescape

# picom &
# flameshot &
polybar &

pgrep -x sxhkd > /dev/null || sxhkd &

# sxhkd -f 100 &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap           3

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer false

bspc config pointer_motion_interval	7ms

bspc config ignore_ewmh_focus    true
bspc rule -a Chromium follow=off focus=off
bspc rule -a Gimp desktop='^8' state=floating follow=on
# bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey # manage=off
