# Chord mappings for chord_daemon.py.
#
# Hold PrtSc, type the sequence, release PrtSc to emit the value.
# Order matters. Sequence keys should be plain letters/digits.
# The output string can contain any printable character.
#
# After editing, reload without restart:
#   systemctl --user reload chord-daemon
# or:
#   pkill -HUP -f chord_daemon.py

MAPPINGS: dict[str, str] = {
    "a":   "and",
    "ab":  "able",
    "ad":  "that",
    "af":  "after",
    "an":  "anti",
    "anl": "analyze",
    "anls":"analysis",
    "as":  "thing",
    "at":  "ation",
    "b":   "by",
    "ca":  "cause",
    "ch":  "change",
    "cn":  "counter",
    "co":  "contra",
    "cos": "coverage",
    "di":  "dict",
    "df":  "with",
    "e":   "end",
    "er":  "their",
    "ef":  "effect",
    "en":  "ence",
    "f":   "for",
    "fd":  "from",
    "fo":  "fully",
    "fu":  "further",
    "h":   "has",
    "ha":  "have",
    "he":  "here",
    "i":   "is",
    "ib":  "ible",
    "id":  "ideally",
    "ig":  "ing",
    "il":  "ility",
    "imp": "improvement",
    "in":  "inter",
    "iow": "though",
    "l":   "like",
    "m":   "may",
    "mi":  "might",
    "n":   "not",
    "nc":  "ance",
    "ne":  "because",
    "o":   "ously",
    "ok":  "out",
    "od":  "order",
    "or":  "ory",
    "ot":  "other",
    "ou":  "ound",
    "ow":  "know",
    "p":   "people",
    "t":   "the",
    "te":  "there",
    "th":  "this",
    "ti":  "tion",
    "tm":  "time",
    "tr":  "trans",
    "s":   "super",
    "sa":  "same",
    "sh":  "such",
    "si":  "similar",
    "sn":  "since",
    "so":  "some",
    "w":   "was",
    "we":  "were",
    "wh":  "what",
    "wi":  "with",
    "wo":  "would",
    "wn":  "when",

    # we use "p" instead of "y" because "y" is difficult to reach on the right hand
    "po":  "you",
}
