# Chord mappings for chord_daemon.py.
#
# Hold PrtSc, type the sequence, release PrtSc to emit the value.
# Order matters. Sequence keys should be plain letters/digits.
# The output string can contain any printable character.
#
# The daemon auto-reloads this file the next time you press PrtSc — just
# save and use. To force a reload without pressing PrtSc:
#   pkill -HUP -f chord_daemon.py

MAPPINGS: dict[str, str] = {
    "a":   "and",
    "ab":  "able",
    "abo": "about",
    "ad":  "that",
    "adf": "added",
    "af":  "after",
    "ag":  "again",
    "an":  "anti",
    "ano": "anything",
    "anp": "another",
    "anl": "analyze",
    "anls":"analysis",
    "aro": "around",
    "as":  "thing",
    "at":  "ation",
    "b":   "by",
    "bas": "based",
    "bo":  "but",
    "bi":  "build",
    "ca":  "cause",
    "cal": "calcula",
    "cap": "capture",
    "capo":"capabili",
    "ch":  "change",
    "cn":  "counter",
    "co":  "could",
    "con": "construct",
    "com": "common",
    "cur": "current",
    "da":  "data",
    "di":  "dict",
    "dif": "different",
    "difj":"difference",
    "dms": "demonstrate",
    "doc": "document",
    "dsi": "describe",
    "dto": "determine",
    "dv":  "deriva",
    "e":   "end",
    "er":  "their",
    "ero": "exception",
    "ef":  "effect",
    "en":  "ence",
    "eo":  "they",
    "f":   "for",
    "fd":  "from",
    "fi":  "find",
    "fo":  "fully",
    "fol": "following",
    "fu":  "further",
    "fun": "function",
    "func":"functionality",
    "g":   "are",
    "gr":  "graph",
    "gu":  "guideline",
    "h":   "has",
    "ha":  "have",
    "hd":  "had",
    "he":  "here",
    "i":   "is",
    "ib":  "ible",
    "id":  "ideally",
    "ig":  "ing",
    "ink": "think",
    "il":  "ility",
    "imp": "improvement",
    "in":  "inter",
    "inc": "include",
    "iow": "though",
    "is":  "insert",
    "j":   "just",
    "jo":  "join",
    "k":   "than",
    "kl":  "then",
    "l":   "like",
    "la":  "last",
    "les": "tables",
    "m":   "may",
    "ma":  "many",
    "mc":  "much",
    "me":  "ment",
    "met": "method",
    "mes": "message",
    "mea": "measure",
    "mi":  "might",
    "mir": "mirror",
    "mk":  "make",
    "mkd": "made",
    "mkl": "making",
    "mo":  "more",
    "mos": "MOSFET",
    "ms":  "most",
    "n":   "not",
    "nc":  "ance",
    "ne":  "because",
    "nfd": "need",
    "ndf": "needed",
    "o":   "on",
    "od":  "order",
    "oij": "together",
    "oj":  "object",
    "ok":  "out",
    "ope": "operating",
    "or":  "ory",
    "ot":  "other",
    "ou":  "out",
    "ow":  "know",
    "p":   "put",
    "pe":  "type",
    "pi":  "point",
    "poe": "people",
    "por": "procedure",
    "pot": "potentiometer",
    "pr":  "pretty",
    "pri": "prioritize",
    "q":   "ed",
    "r":   "my",
    "rew": "create",
    "s":   "super",
    "sa":  "same",
    "sat": "saturation",
    "satu":"saturday",
    "sb":  "subject",
    "se":  "section",
    "set": "setting",
    "sh":  "should",
    "si":  "similar",
    "simp":"simply",
    "sj":  "say",
    "sm":  "symbol",
    "sn":  "since",
    "so":  "some",
    "t":   "the",
    "ta":  "that",
    "te":  "there",
    "th":  "this",
    "tho": "though",
    "thp": "thought",
    "trh": "through",
    "trho":"throughout",
    "ti":  "tion",
    "tk":  "task",
    "tm":  "time",
    "tr":  "them",
    "trio":"triode",
    "trno":"transistor",
    "tw":  "these",
    "u":   "use",
    "ui":  "using",
    "v":   "of",
    "va":  "value",
    "vo":  "voltage",
    "ver": "verify",
    "ud":  "used",
    "w":   "was",
    "wa":  "way",
    "wc":  "which",
    "we":  "were",
    "wer": "where",
    "wh":  "what",
    "wi":  "with",
    "wl":  "will",
    "wn":  "when",
    "wo":  "would",
    "wr":  "write",

    # we use "p" instead of "y" because "y" is difficult to reach on the right hand
    "po":  "you",
}
