# Chord mappings for chord_daemon.py.
#
# Hold PrtSc, type the sequence, release PrtSc to emit the value.
# Order matters. Sequence keys should be plain letters/digits.
# The output string can contain any printable character.
#
# The daemon auto-reloads this file the next time you press PrtSc — just
# save and use. To force a reload without pressing PrtSc:
#   pkill -HUP -f chord_daemon.py

MAPPINGS: dict[str, str] = {
    "a":   "and",
    "ab":  "able",
    "abo": "about",
    "ad":  "that",
    "af":  "after",
    "ag":  "again",
    "an":  "anti",
    "ano": "anything",
    "anl": "analyze",
    "anls":"analysis",
    "aro": "around",
    "as":  "thing",
    "at":  "ation",
    "b":   "by",
    "bo":  "but",
    "ca":  "cause",
    "cal": "calcula",
    "cap": "capture",
    "capo":"capabili",
    "ch":  "change",
    "cn":  "counter",
    "co":  "could",
    "con": "construct",
    "com": "common",
    "cur": "current",
    "di":  "dict",
    "da":  "data",
    "dms": "demonstrate",
    "dsi": "describe",
    "dv":  "deriva",
    "doc": "document",
    "e":   "end",
    "er":  "their",
    "ef":  "effect",
    "en":  "ence",
    "eo":  "they",
    "f":   "for",
    "fd":  "from",
    "fo":  "fully",
    "fol": "following",
    "fu":  "further",
    "gr":  "graphs",
    "h":   "has",
    "ha":  "have",
    "he":  "here",
    "i":   "is",
    "ib":  "ible",
    "id":  "ideally",
    "ig":  "ing",
    "ink": "think",
    "il":  "ility",
    "imp": "improvement",
    "in":  "inter",
    "iow": "though",
    "is":  "insert",
    "j":   "just",
    "jo":  "join",
    "k":   "than",
    "kl":  "then",
    "l":   "like",
    "la":  "last",
    "les": "tables",
    "m":   "may",
    "ma":  "many",
    "me":  "ment",
    "mes": "message",
    "mea": "measure",
    "mi":  "might",
    "mir":  "might",
    "mo":  "more",
    "mos": "MOSFET",
    "n":   "not",
    "nc":  "ance",
    "ne":  "because",
    "nfd": "need",
    "ndf": "needed",
    "o":   "on",
    "oj": "objective",
    "ok":  "out",
    "od":  "order",
    "or":  "ory",
    "ot":  "other",
    "ou":  "ound",
    "oij": "together",
    "ow":  "know",
    "p":   "put",
    "pi":  "point",
    "poe": "people",
    "por": "procedure",
    "q":   "ed",
    "r":   "my",
    "rew": "create",
    "s":   "super",
    "sa":  "same",
    "se":  "section",
    "sh":  "should",
    "si":  "similar",
    "sn":  "since",
    "so":  "some",
    "t":   "the",
    "ta":  "that",
    "te":  "there",
    "th":  "this",
    "ti":  "tion",
    "tk":  "task",
    "tm":  "time",
    "tr":  "them",
    "tw":  "these",
    "u":   "use",
    "ud":  "used",
    "w":   "was",
    "wc":  "which",
    "we":  "were",
    "wh":  "what",
    "wi":  "with",
    "wl":  "will",
    "wn":  "when",
    "wo":  "would",
    "wr":  "write",

    # we use "p" instead of "y" because "y" is difficult to reach on the right hand
    "po":  "you",
}
